### ISSUE TITLE
Feat: icon / Cart 컴포넌트

### ISSUE THREAD

**Issue by arayofseonshine** [FRONTENDSCHOOL10/1uminofight#8]
### **⬛ 페이지**
메인페이지, 상품리스트, 상품 상세페이지

### **⬛ 작업 내용**
- icon / Cart 컨포넌트 구현
    - 메인페이지: 장바구니' 버튼을 클릭하면 (사용자가 장바구니에 항목을 담으면) 장바구니 페이지에 랜더링이 되도록 구현 (로컬 스토리지)
    - 메인페이지: 장바구니' 버튼 hover시 장바구니 버튼 색 변경
    - 상품리스트: 장바구니' 버튼을 클릭하면 (사용자가 장바구니에 항목을 담으면) 장바구니 페이지에 랜더링이 되도록 구현 (로컬 스토리지)
    - 상품 상세페이지: 사용자가 장바구니에 항목을 담으면 장바구니 페이지에 랜더링이 되도록 구현 (로컬 스토리지)

### **⬛ 참고 자료(선택)**
![image](https://github.com/FRONTENDSCHOOL10/1uminofight/assets/148742038/8af67f23-3335-47e6-b948-71470781f828)

**Comment by SohnSW** [comment]
페이지 구성 중 해야하는 작업이라 넘겼습니다.
